# Generated by Django 5.1.6 on 2025-02-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_watered", models.DateField(auto_now_add=True)),
                ("watering_frequency", models.IntegerField()),
                ("notes", models.TextField()),
            ],
        ),
    ]
